version: '3'
services:
  httpbin:
    image: docker.io/kennethreitz/httpbin:latest
    ports:
      - "8000:80"

  toxiproxy:
    image: docker.io/shopify/toxiproxy:latest
    ports:
      - "8474:8474"
      - "8001:8001"
